-- https://github.com/lewis6991/gitsigns.nvim
-- 在标志列显示 Git 变更标记, 并提供丰富操作
return {
	"lewis6991/gitsigns.nvim",
	event = { "BufReadPre", "BufNewFile" },
	main = "gitsigns",
	opts = {
		--        on_attach = function(bufnr)
		--            local gitsigns = require("gitsigns")
		--            local function map(mode, l, r, opts)
		--                opts = opts or {}
		--                opts.buffer = bufnr
		--                vim.keymap.set(mode, l, r, opts)
		--            end
		--            -- Navigation
		--            map("n", "]c", function()
		--                if vim.wo.diff then
		--                    vim.cmd.normal({
		--                        "]c",
		--                        bang = true
		--                    })
		--                else
		--                    gitsigns.nav_hunk("next")
		--                end
		--            end, {
		--                desc = "跳转到下一个改动"
		--            })

		--            map("n", "[c", function()
		--                if vim.wo.diff then
		--                    vim.cmd.normal({
		--                        "[c",
		--                        bang = true
		--                    })
		--                else
		--                    gitsigns.nav_hunk("prev")
		--                end
		--            end, {
		--                desc = "跳转到上一个改动"
		--            })

		--            -- Actions
		--            map("v", "<leader>hs", function()
		--                gitsigns.stage_hunk({vim.fn.line("."), vim.fn.line("v")})
		--            end, {
		--                desc = "暂存当前块"
		--            })
		--            map("v", "<leader>hr", function()
		--                gitsigns.reset_hunk({vim.fn.line("."), vim.fn.line("v")})
		--            end, {
		--                desc = "重置当前块"
		--            })
		--            map("n", "<leader>hs", gitsigns.stage_hunk, {
		--                desc = "暂存当前块"
		--            })
		--            map("n", "<leader>hr", gitsigns.reset_hunk, {
		--                desc = "重置当前块"
		--            })
		--            map("n", "<leader>hS", gitsigns.stage_buffer, {
		--                desc = "暂存当前缓冲区"
		--            })
		--            map("n", "<leader>hu", gitsigns.undo_stage_hunk, {
		--                desc = "撤销暂存当前块"
		--            })
		--            map("n", "<leader>hR", gitsigns.reset_buffer, {
		--                desc = "重置缓冲区"
		--            })
		--            map("n", "<leader>hp", gitsigns.preview_hunk, {
		--                desc = "预览当前块"
		--            })
		--            map("n", "<leader>hb", gitsigns.blame_line, {
		--                desc = "查看当前行 Blame"
		--            })
		--            map("n", "<leader>hd", gitsigns.diffthis, {
		--                desc = "与索引比较差异"
		--            })
		--            map("n", "<leader>hD", function()
		--                gitsigns.diffthis("@")
		--            end, {
		--                desc = "与上一次提交比较差异"
		--            })
		--            -- Toggles
		--            map("n", "<leader>tb", gitsigns.toggle_current_line_blame, {
		--                desc = "切换行内 Blame"
		--            })
		--            map("n", "<leader>tD", gitsigns.toggle_deleted, {
		--                desc = "切换显示已删除"
		--            })
		--        end
	},
}
